spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/FittnessAiApp/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/Activity/**

        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations/**
filter:
  keycloak:
    enabled: false

server:
  port: 3499

